name: bluetooth_utils
description: "Bluetooth Utils."
publish_to: 'none'
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: any
  flutter_blue_plus_platform_interface: any
  permission_handler: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

resolution: workspace
