name: path_provider_utils
description: "Path Provider Utils."
publish_to: 'none'
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

resolution: workspace
