name: seat_cushion_presentation
description: "Seat Cushion Presentation."
publish_to: 'none'
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  copy_with_extension: any
  copy_with_extension_gen: any
  equatable: any
  json_annotation: any
  provider: any
  simple_3d: any
  simple_3d_renderer: any
  synchronized: any
  util_simple_3d: any
  theme_tailor: any
  theme_tailor_annotation: any

  # Domains
  seat_cushion: any

  # Packages
  stream_utils: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  json_serializable: any

flutter:
  uses-material-design: true
  generate: true

resolution: workspace